services:
    grafana:
        ports:
            - 3033:3000
        container_name: grafana
        restart: unless-stopped
        environment:
            - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
        user: '0'
        volumes:
            - ${CONFIG_STORAGE_LOCATION}/grafana-storage:/var/lib/grafana
        image: grafana/grafana-oss
    influxdb:
        ports:
            - 8069:8086
        container_name: influxdb
        restart: unless-stopped
        volumes:
            - ${CONFIG_STORAGE_LOCATION}/influxdb/data:/var/lib/influxdb2
            - ${CONFIG_STORAGE_LOCATION}/influxdb/config:/etc/influxdb2
        image: influxdb:2