services:
    gluetun:
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        environment:
            - VPN_SERVICE_PROVIDER=${proxy_provider}
            - VPN_TYPE=wireguard
              # get the wg private key from https://mullvad.net/en/account/wireguard-config
              # generate key, then download any .conf. use the key and ip from that .conf below
            - WIREGUARD_PRIVATE_KEY=${proxy_private_key}
            - WIREGUARD_ADDRESSES=${proxy_address}
            - SERVER_CITIES=Adelaide,Amsterdam,"Ashburn VA",Athens,"Atlanta GA",Auckland,Belgrade,Berlin,Bogota,Bratislava,Brisbane,Brussels,Bucharest,Budapest,Calgary,"Chicago IL",Chisinau,Copenhagen,"Dallas TX","Denver CO",Dubai,Dublin,Dusseldorf,Frankfurt,Gothenburg,Helsinki,"Hong Kong","Houston TX",Johannesburg,Kyiv,Lisbon,London,"Los Angeles CA",Luxembourg,Madrid,Malm√∂,Manchester,Marseille,Melbourne,"Miami FL",Milan,Montreal,"New York NY",Osaka,Oslo,Paris,Perth,"Phoenix AZ",Prague,"Raleigh NC",Riga,"Salt Lake City UT","San Jose CA","Sao Paulo","Seattle WA","Secaucus NJ",Singapore,Skopje,Sofia,Stavanger,Stockholm,Sydney,Tallinn,"Tel Aviv",Tirana,Tokyo,Toronto,Vancouver,Vienna,Warsaw,Zagreb,Zurich
            - SHADOWSOCKS=on
            - SHADOWSOCKS_LOG=on
            - SHADOWSOCKS_PASSWORD=${proxy_shadowsocks_password}
            - DOT=off
            - DNS_PLAINTEXT_ADDRESS=${proxy_dns}
        ports:
            - 8888:8888/tcp # HTTP proxy
            - 8388:8388/tcp # Shadowsocks
            - 8388:8388/udp # Shadowsocks
            - 1080:1080 # socks5
        image: qmcgaw/gluetun
    socks5:
        container_name: socks5
        environment:
#            - PROXY_USER=user
#            - PROXY_PASSWORD=pass
            - PROXY_PORT=1080
        image: serjs/go-socks5-proxy
        network_mode: service:gluetun
        depends_on:
          gluetun:
            condition: service_healthy
    xmrig:
        restart: unless-stopped
        image: miningcontainers/xmrig
        container_name: xmrig
        command: -k --tls -o pool.hashvault.pro:443 -u ${monero_address} --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
        network_mode: service:gluetun
        depends_on:
            gluetun:
                condition: service_healthy
# see restart_proxy.sh to auto rotate IP's using cron
# also, the curl command can be used to ensure it is running
